---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Cloud Native Infrastructure"
keywords:    "Cloud Native Infrastructure O'Rielly Book"
description: "A book by Justin Garrison and Kris Nova about how to run infrastructure in the cloud the cloud native way"
source_link: "http://www.cnibook.info"
#favicon:     "img/favicon.ico"
#touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: UA-104383394-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

#plugins: [jekyll-seo-tag]
